services:
  - type: web
    name: aggregator-server
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn scraper:app --host 0.0.0.0 --port 10000